export const profile = "/images/AngkorProfile.jpg";

export const favoriteSongs = [
  // {
  //   id: "1",
  //   title: "មេឃបើកថ្ងៃ",
  //   artist: "KWAN",
  //   featuring: "Vannda",
  //   duration: "3:37",
  //   genre: "Khmer Pop",
  //   year: "2023",
  //   youtubeUrl: "https://www.youtube.com/watch?v=toJ4nn_WmeQ",
  //   spotifyUrl: "https://open.spotify.com/track/6HWbL3uNRzkisSZoyqydaT",
  //   audioUrl: "/audios/berkthgai.mp3",
  //   coverColor: "from-orange-400 to-red-500",
  //   language: "Khmer",
  //   mood: "Uplifting",
  //   coverImageUrl: "https://i.ytimg.com/vi/-9iQ_gmFjmA/maxresdefault.jpg",
  // },
  // {
  //   id: "2",
  //   title: "ឆាឆាឆា (CHA CHA CHA)",
  //   artist: "2MDIE",
  //   duration: "4:48",
  //   genre: "Khmer Hip-Hop",
  //   year: "2024",
  //   youtubeUrl: "https://www.youtube.com/watch?v=r67B4cS-oCo",
  //   spotifyUrl: "https://open.spotify.com/track/68EWw08VyD1oZwofVltpjv",
  //   audioUrl: "/audios/2MDIE.mp3",
  //   coverColor: "from-purple-400 to-pink-500",
  //   language: "Khmer",
  //   mood: "Energetic",
  //   coverImageUrl: "https://i.ytimg.com/vi/r67B4cS-oCo/maxresdefault.jpg",
  // },
  {
    id: "2",
    title: "អាត្មា (AH THMA)",
    artist: "VANNDA",
    duration: "4:55",
    genre: "Khmer Hip-Hop",
    year: "2025",
    youtubeUrl:
      "https://www.youtube.com/watch?v=RvP-6ynP1tI&list=RDRvP-6ynP1tI&start_radio=1",
    spotifyUrl: "https://open.spotify.com/album/6euzRA1Vh0KsjPjkksjYYB",
    audioUrl: "/audios/ahthma.mp3",
    coverColor: "from-orange-400 to-red-500",
    language: "Khmer",
    mood: "Uplifting",
    coverImageUrl: "https://i.ytimg.com/vi/RvP-6ynP1tI/maxresdefault.jpg",
  },
  // {
  //   id: "3",
  //   title: "Starboy",
  //   artist: "The Weeknd",
  //   featuring: "Daft Punk",
  //   duration: "3:50",
  //   genre: "Pop",
  //   year: "2016",
  //   youtubeUrl: "https://www.youtube.com/watch?v=34Na4j8AVgA",
  //   spotifyUrl: "https://open.spotify.com/track/7MXVkk9YMctZqd1Srtv4MB",
  //   audioUrl: "/audios/Starboy.mp3",
  //   coverColor: "from-blue-900 to-yellow-500",
  //   language: "English",
  //   mood: "Chill",
  //   coverImageUrl:
  //     "https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/e2/61/f8/e261f8c1-73db-9a7a-c89e-1068f19970e0/16UMGIM67863.rgb.jpg/1200x630bb.jpg",
  // },
  {
    id: "3",
    title: "About You",
    artist: "The 1975",
    featuring: null,
    duration: "5:26",
    genre: "Alternative Rock",
    year: "2022",
    youtubeUrl: "https://www.youtube.com/watch?v=tGv7CUutzqU",
    spotifyUrl: "https://open.spotify.com/artist/3mIj9lX2MWuHmhNCA7LSCW",
    audioUrl: "/audios/The1975.mp3",
    coverColor: "from-gray-900 to-indigo-700",
    language: "English",
    mood: "Melancholic",
    coverImageUrl:
      "https://i.scdn.co/image/ab67616d00001e0200702474f8e0e2b6155d48e3",
  },
  {
    id: "4",
    title: "Multo",
    artist: "Cup of Joe",
    featuring: null,
    duration: "4:12",
    genre: "OPM / Alternative",
    year: "2023",
    youtubeUrl: "https://www.youtube.com/watch?v=Rht8rS4cR1s&list=RDRht8rS4cR1s",
    spotifyUrl: "https://open.spotify.com/track/4cBm8rv2B5BJWU2pDaHVbF",
    audioUrl: "/audios/Multo.mp3",
    coverColor: "from-emerald-900 to-teal-600",
    language: "Filipino",
    mood: "Emotional",
    coverImageUrl:
      "https://i.scdn.co/image/ab67616d0000b273394048503e3be0e65e962638",
  },
];

const getImage = (name: string): string => `/images/${name}`;

export const images = [
  { url: getImage("Preaskhan.JPG") },
  { url: getImage("AngkorTake.JPG") },
  // { url: getImage("selfie.jpg") },
  { url: getImage("Jroyjangvar.jpg") },
  // { url: getImage("FromBuilding.jpg") },
  { url: getImage("Krrirom.jpg") },
  { url: getImage("PresentCADT.jpg") },
  { url: getImage("SunsetRUPP.jpg") },
  { url: getImage("KNY.jpg") },
  { url: getImage("Bokor.jpg") },
  { url: getImage("Jreav.JPG") },
];
