export const favoriteSongs = [
  {
    id: "1",
    title: "មេឃបើកថ្ងៃ",
    artist: "KWAN",
    featuring: "Vannda",
    duration: "3:37",
    genre: "Khmer Pop",
    year: "2023",
    youtubeUrl: "https://www.youtube.com/watch?v=toJ4nn_WmeQ",
    spotifyUrl: "https://open.spotify.com/track/6HWbL3uNRzkisSZoyqydaT",
    audioUrl: "/audios/berkthgai.mp3",
    coverColor: "from-orange-400 to-red-500",
    language: "Khmer",
    mood: "Uplifting",
    coverImageUrl: "https://i.ytimg.com/vi/-9iQ_gmFjmA/maxresdefault.jpg",
  },
  // {
  //   id: "2",
  //   title: "ឆាឆាឆា (CHA CHA CHA)",
  //   artist: "2MDIE",
  //   duration: "4:48",
  //   genre: "Khmer Hip-Hop",
  //   year: "2024",
  //   youtubeUrl: "https://www.youtube.com/watch?v=r67B4cS-oCo",
  //   spotifyUrl: "https://open.spotify.com/track/68EWw08VyD1oZwofVltpjv",
  //   audioUrl: "/audios/2MDIE.mp3",
  //   coverColor: "from-purple-400 to-pink-500",
  //   language: "Khmer",
  //   mood: "Energetic",
  //   coverImageUrl: "https://i.ytimg.com/vi/r67B4cS-oCo/maxresdefault.jpg",
  // },
  {
    id: "2",
    title: "អាត្មា (AH THMA)",
    artist: "VANNDA",
    duration: "4:55",
    genre: "Khmer Hip-Hop",
    year: "2025",
    youtubeUrl:
      "https://www.youtube.com/watch?v=RvP-6ynP1tI&list=RDRvP-6ynP1tI&start_radio=1",
    spotifyUrl: "https://open.spotify.com/album/6euzRA1Vh0KsjPjkksjYYB",
    audioUrl: "/audios/ahthma.mp3",
    coverColor: "from-orange-400 to-red-500",
    language: "Khmer",
    mood: "Uplifting",
    coverImageUrl: "https://i.ytimg.com/vi/RvP-6ynP1tI/maxresdefault.jpg",
  },
  {
    id: "3",
    title: "Starboy",
    artist: "The Weeknd",
    featuring: "Daft Punk",
    duration: "3:50",
    genre: "Pop",
    year: "2016",
    youtubeUrl: "https://www.youtube.com/watch?v=34Na4j8AVgA",
    spotifyUrl: "https://open.spotify.com/track/7MXVkk9YMctZqd1Srtv4MB",
    audioUrl: "/audios/Starboy.mp3",
    coverColor: "from-blue-900 to-yellow-500",
    language: "English",
    mood: "Chill",
    coverImageUrl:
      "https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/e2/61/f8/e261f8c1-73db-9a7a-c89e-1068f19970e0/16UMGIM67863.rgb.jpg/1200x630bb.jpg",
  },
];

export const images = [
  {
    url: "/images/selfie.jpg",
    // title: "Selfie Vibes",
  },
  {
    url: "/images/Jroyjangvar.jpg",
    // title: "Jroyjangvar Feels",
  },
  {
    url: "/images/FromBuilding.jpg",
    // title: "Olampia Views",
  },
  {
    url: "/images/Krrirom.jpg",
    // title: "Krrirom Adventures",
  },
  {
    url: "/images/PresentCADT.jpg",
    // title: "CADT Moments",
  },
  {
    url: "/images/SunsetRUPP.jpg",
    // title: "Golden Hour @ RUPP",
  },
  {
    url: "/images/KNY.jpg",
    // title: "KNY 2025 Vibes",
  },
];
